# Generated by Django 5.2.16 on 2026-07-28 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('theme', models.CharField(choices=[('neutral', 'Neutrali'), ('magic_academy', 'Magijos akademija'), ('block_world', 'Blokų pasaulis')], default='neutral', max_length=32)),
                ('pin_hash', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('min_balance', models.IntegerField(default=-100)),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FamilySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, default='', max_length=80)),
                ('currency_name', models.CharField(default='Tokenai', max_length=32)),
                ('default_min_balance', models.IntegerField(default=-100)),
            ],
            options={
                'verbose_name': 'šeimos nustatymai',
                'verbose_name_plural': 'šeimos nustatymai',
            },
        ),
        migrations.CreateModel(
            name='PenaltyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('sparkles', 'Žvaigždutės'), ('broom', 'Šluota'), ('book', 'Knyga'), ('bed', 'Lova'), ('dish', 'Indai'), ('paw', 'Augintinis'), ('school', 'Mokykla'), ('screen', 'Ekranas'), ('gift', 'Dovana'), ('star', 'Žvaigždė')], default='star', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(validators=[django.core.validators.MaxValueValidator(-1)])),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('sparkles', 'Žvaigždutės'), ('broom', 'Šluota'), ('book', 'Knyga'), ('bed', 'Lova'), ('dish', 'Indai'), ('paw', 'Augintinis'), ('school', 'Mokykla'), ('screen', 'Ekranas'), ('gift', 'Dovana'), ('star', 'Žvaigždė')], default='star', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('sparkles', 'Žvaigždutės'), ('broom', 'Šluota'), ('book', 'Knyga'), ('bed', 'Lova'), ('dish', 'Indai'), ('paw', 'Augintinis'), ('school', 'Mokykla'), ('screen', 'Ekranas'), ('gift', 'Dovana'), ('star', 'Žvaigždė')], default='star', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('kind', models.CharField(choices=[('task', 'Darbas'), ('penalty', 'Bausmė'), ('reward', 'Prizas'), ('adjustment', 'Korekcija')], max_length=16)),
                ('description', models.CharField(max_length=240)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='economy.childprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('reward', 'Prizas'), ('goal', 'Taupymo tikslas')], max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('sparkles', 'Žvaigždutės'), ('broom', 'Šluota'), ('book', 'Knyga'), ('bed', 'Lova'), ('dish', 'Indai'), ('paw', 'Augintinis'), ('school', 'Mokykla'), ('screen', 'Ekranas'), ('gift', 'Dovana'), ('star', 'Žvaigždė')], default='star', max_length=32)),
                ('suggested_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('final_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Laukia'), ('approved', 'Patvirtinta'), ('rejected', 'Atmesta'), ('cancelled', 'Atšaukta')], default='pending', max_length=16)),
                ('parent_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='economy.childprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(choices=[('sparkles', 'Žvaigždutės'), ('broom', 'Šluota'), ('book', 'Knyga'), ('bed', 'Lova'), ('dish', 'Indai'), ('paw', 'Augintinis'), ('school', 'Mokykla'), ('screen', 'Ekranas'), ('gift', 'Dovana'), ('star', 'Žvaigždė')], default='star', max_length=32)),
                ('target_amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Aktyvus'), ('completed', 'Pasiektas'), ('cancelled', 'Atšauktas')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='economy.childprofile')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_title', models.CharField(max_length=120)),
                ('cost_snapshot', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Laukia'), ('approved', 'Patvirtinta'), ('rejected', 'Atmesta'), ('cancelled', 'Atšaukta')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_requests', to='economy.childprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_reward_requests', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='economy.reward')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('child', 'reward'), name='unique_pending_reward_per_child')],
            },
        ),
        migrations.CreateModel(
            name='TaskClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=120)),
                ('reward_snapshot', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Laukia'), ('approved', 'Patvirtinta'), ('rejected', 'Atmesta'), ('cancelled', 'Atšaukta')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_claims', to='economy.childprofile')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_task_claims', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='economy.task')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('child', 'task'), name='unique_pending_task_per_child')],
            },
        ),
    ]
