# Generated by Django 5.2.16 on 2026-07-28 17:21

from django.db import migrations, models


LEGACY_ICONS = {
    "sparkles": "✨",
    "broom": "🧹",
    "book": "📚",
    "bed": "🛏️",
    "dish": "🍽️",
    "paw": "🐾",
    "school": "🎓",
    "screen": "📱",
    "gift": "🎁",
    "star": "⭐",
}


def convert_legacy_icons(apps, schema_editor):
    for model_name in ("Task", "PenaltyTemplate", "Reward", "Proposal", "SavingsGoal"):
        model = apps.get_model("economy", model_name)
        for old_value, emoji in LEGACY_ICONS.items():
            model.objects.filter(icon=old_value).update(icon=emoji)


def restore_legacy_icons(apps, schema_editor):
    reverse_icons = {emoji: old_value for old_value, emoji in LEGACY_ICONS.items()}
    for model_name in ("Task", "PenaltyTemplate", "Reward", "Proposal", "SavingsGoal"):
        model = apps.get_model("economy", model_name)
        for emoji, old_value in reverse_icons.items():
            model.objects.filter(icon=emoji).update(icon=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_familysettings_recovery_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='penaltytemplate',
            name='icon',
            field=models.CharField(default='⭐', max_length=32),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='icon',
            field=models.CharField(default='⭐', max_length=32),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon',
            field=models.CharField(default='⭐', max_length=32),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='icon',
            field=models.CharField(default='⭐', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='icon',
            field=models.CharField(default='⭐', max_length=32),
        ),
        migrations.RunPython(convert_legacy_icons, restore_legacy_icons),
    ]
