# Generated by Django 5.2.16 on 2026-07-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_childprofile_avatar_alter_penaltytemplate_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='vocative_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('task', 'Darbas'), ('penalty', 'Nuoboda'), ('reward', 'Prizas'), ('adjustment', 'Korekcija')], max_length=16),
        ),
    ]
