# Generated by Django 5.2.16 on 2026-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_childprofile_vocative_name_alter_ledgerentry_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('task', 'Darbas'), ('penalty', 'Nuobauda'), ('reward', 'Prizas'), ('adjustment', 'Korekcija')], max_length=16),
        ),
    ]
