# Generated by Django 5.2.16 on 2026-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_alter_ledgerentry_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltytemplate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reward',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
