# Generated by Django 5.2.16 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("economy", "0007_international_defaults"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="familysettings",
            options={"verbose_name": "family settings", "verbose_name_plural": "family settings"},
        ),
        migrations.AlterField(
            model_name="childprofile",
            name="theme",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("magic_academy", "Magic Academy"),
                    ("block_world", "Block World"),
                ],
                default="neutral",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("task", "Task"),
                    ("penalty", "Penalty"),
                    ("reward", "Reward"),
                    ("adjustment", "Adjustment"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_type",
            field=models.CharField(
                choices=[("reward", "Reward"), ("goal", "Savings goal")],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="rewardrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="taskclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
