# Generated by Django 5.2.16 on 2026-07-29 07:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0009_family_name_and_theme_onboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskclaim',
            name='unique_pending_task_per_child',
        ),
        migrations.AddField(
            model_name='familysettings',
            name='evidence_retention_days',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Keep indefinitely'), (7, '7 days'), (30, '30 days'), (90, '90 days')], default=30),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='photo_bonus_points',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='economy.childprofile'),
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='evidence_image',
            field=models.ImageField(blank=True, upload_to='task-evidence/full/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='evidence_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='evidence_thumbnail',
            field=models.ImageField(blank=True, upload_to='task-evidence/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='evidence_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='photo_bonus_snapshot',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='taskclaim',
            name='revision_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='familysettings',
            name='currency_name',
            field=models.CharField(default='Points', max_length=32),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_changes', 'Needs changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_changes', 'Needs changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='taskclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_changes', 'Needs changes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', True), ('user__isnull', False)), models.Q(('child__isnull', False), ('user__isnull', True)), _connector='OR'), name='push_subscription_has_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='taskclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'needs_changes'])), fields=('child', 'task'), name='unique_pending_task_per_child'),
        ),
    ]
