# Generated by Django 5.2.16 on 2026-07-29 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_task_evidence_and_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familysettings',
            name='feedback_screenshot_retention_days',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Keep indefinitely'), (7, '7 days'), (30, '30 days'), (90, '90 days')], default=90),
        ),
        migrations.CreateModel(
            name='FeedbackReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bug', 'Problem'), ('idea', 'Suggestion')], default='bug', max_length=12)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('resolved', 'Resolved')], default='new', max_length=12)),
                ('description', models.TextField(max_length=2000)),
                ('reporter_name', models.CharField(max_length=150)),
                ('reporter_role', models.CharField(max_length=12)),
                ('family_name', models.CharField(blank=True, max_length=80)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('app_version', models.CharField(max_length=32)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('theme', models.CharField(blank=True, max_length=32)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('screenshot', models.ImageField(blank=True, upload_to='feedback/screenshots/%Y/%m/')),
                ('screenshot_purged_at', models.DateTimeField(blank=True, null=True)),
                ('email_notified_at', models.DateTimeField(blank=True, null=True)),
                ('email_error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to='economy.childprofile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='economy_fee_status_da34d0_idx'), models.Index(fields=['report_type', '-created_at'], name='economy_fee_report__ca780e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('child__isnull', True), ('parent__isnull', False)), models.Q(('child__isnull', False), ('parent__isnull', True)), _connector='OR'), name='feedback_report_has_one_reporter')],
            },
        ),
    ]
