# Generated by Django 5.2.16 on 2026-07-29 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0011_feedback_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familysettings',
            name='birthday_points',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='theme',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('magic_academy', 'Magic Academy'), ('block_world', 'Block World'), ('hero_hq', 'Superhero HQ'), ('art_studio', 'Art Studio'), ('panda_pet', 'Panda World')], default='neutral', max_length=32),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('task', 'Task'), ('penalty', 'Penalty'), ('reward', 'Reward'), ('adjustment', 'Adjustment'), ('gift', 'Gift'), ('birthday', 'Birthday')], max_length=16),
        ),
        migrations.CreateModel(
            name='BirthdayAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('points', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birthday_awards', to='economy.childprofile')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birthday_award', to='economy.ledgerentry')),
            ],
            options={
                'ordering': ['-year', '-awarded_at'],
                'constraints': [models.UniqueConstraint(fields=('child', 'year'), name='one_birthday_award_per_year')],
            },
        ),
        migrations.CreateModel(
            name='PointGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_point_gifts', to='economy.childprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_point_gifts', to='economy.childprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sender', models.F('recipient')), _negated=True), name='point_gift_different_children'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='point_gift_positive_amount')],
            },
        ),
    ]
