# Generated by Django 5.2.16 on 2026-07-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def mark_existing_birth_dates_initialized(apps, schema_editor):
    ChildProfile = apps.get_model("economy", "ChildProfile")
    ChildProfile.objects.filter(birth_date__isnull=False).update(
        birth_date_initialized=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0012_gifts_birthdays_and_themes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="birth_date_initialized",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_birth_dates_initialized,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="BirthDateChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_birth_date", models.DateField(blank=True, null=True)),
                ("requested_birth_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("needs_changes", "Needs changes"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="birth_date_change_requests",
                        to="economy.childprofile",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decided_birth_date_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-requested_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=Q(status="pending"),
                        fields=("child",),
                        name="one_pending_birth_date_change_per_child",
                    )
                ],
            },
        ),
    ]
