# Generated by Django 5.2.16 on 2026-07-30 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0015_childprofile_random_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='theme',
            field=models.CharField(choices=[('neutral', 'Neutral'), ('magic_academy', 'Magic Academy'), ('block_world', 'Block World'), ('hero_hq', 'Superhero HQ'), ('art_studio', 'Art Studio'), ('panda_pet', 'Panda World'), ('robliux', 'Robliux World')], default='neutral', max_length=32),
        ),
        migrations.CreateModel(
            name='BackupAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('configured', 'Backup settings configured'), ('manual_run', 'Manual backup requested')], max_length=32)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
