# Generated by Django 5.2.16 on 2026-08-10 18:52

import secrets

from django.db import migrations, models


DEVICE_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


def populate_device_codes(apps, schema_editor):
    DeviceToken = apps.get_model("economy", "DeviceToken")
    for device in DeviceToken.objects.filter(device_code__isnull=True).iterator():
        code = "".join(secrets.choice(DEVICE_CODE_ALPHABET) for _ in range(6))
        while DeviceToken.objects.filter(device_code=code).exists():
            code = "".join(secrets.choice(DEVICE_CODE_ALPHABET) for _ in range(6))
        DeviceToken.objects.filter(pk=device.pk).update(device_code=code)


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0025_proposal_goal_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetoken',
            name='device_browser',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_kind',
            field=models.CharField(choices=[('phone', 'Phone'), ('tablet', 'Tablet'), ('computer', 'Computer'), ('unknown', 'Unknown device')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='devicetoken',
            name='device_platform',
            field=models.CharField(default='unknown', max_length=16),
        ),
        migrations.RunPython(populate_device_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_code',
            field=models.CharField(blank=True, editable=False, max_length=6, unique=True),
        ),
    ]
