# Generated by Django 5.2.17 on 2026-08-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0027_push_subscription_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptcounter',
            name='scope',
            field=models.CharField(choices=[('child_pin_device', 'Child PIN by device'), ('child_pin_profile', 'Child PIN by profile'), ('child_pin_ip', 'Child PIN by IP'), ('child_pin_site', 'Child PIN site-wide'), ('parent_login_ip', 'Parent login by IP'), ('parent_login_account', 'Parent login by account'), ('password_reset_ip', 'Password reset by IP'), ('password_reset_account', 'Password reset by account'), ('device_pairing', 'Device pairing'), ('admin_login_ip', 'Admin login by IP'), ('setup_claim_ip', 'Initial setup by IP')], max_length=32),
        ),
    ]
