# Generated by Django 5.2.17 on 2026-08-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0029_taskcompletion_unique_per_child_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('task', 'Task'), ('assigned_task', 'Assigned task'), ('penalty', 'Penalty'), ('reward', 'Reward'), ('lottery', 'Surprise card'), ('adjustment', 'Adjustment'), ('gift', 'Gift'), ('birthday', 'Birthday'), ('savings_transfer', 'Saved to goal'), ('savings_return', 'Returned from goal'), ('goal_completion', 'Goal completion')], max_length=16),
        ),
    ]
