# Generated by Django 5.2.17 on 2026-08-15 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0035_taskclaim_child_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptcounter',
            name='scope',
            field=models.CharField(choices=[('child_pin_device', 'Child PIN by device'), ('child_pin_profile', 'Child PIN by profile'), ('child_pin_ip', 'Child PIN by IP'), ('child_pin_site', 'Child PIN site-wide'), ('parent_login_ip', 'Parent login by IP'), ('parent_login_account', 'Parent login by account'), ('password_reset_ip', 'Password reset by IP'), ('password_reset_account', 'Password reset by account'), ('device_pairing', 'Device pairing'), ('admin_login_ip', 'Admin login by IP'), ('setup_claim_ip', 'Initial setup by IP'), ('caregiver_invite_ip', 'Caregiver invite by IP'), ('caregiver_invite_parent', 'Caregiver invite by parent'), ('caregiver_pin_profile', 'Caregiver PIN by profile'), ('caregiver_pin_ip', 'Caregiver PIN by IP')], max_length=32),
        ),
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('login_code', models.CharField(max_length=16, unique=True)),
                ('pin_hash', models.CharField(max_length=255)),
                ('access_until', models.DateField()),
                ('failed_pin_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('children', models.ManyToManyField(related_name='caregivers', to='economy.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_caregivers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('access_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('children', models.ManyToManyField(related_name='caregiver_invites', to='economy.childprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_invites', to=settings.AUTH_USER_MODEL)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='economy.caregiverprofile')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
